### PR TITLE
Week 1: Module 1: Set up a 'Hello Microverse' project

### PR DESCRIPTION
**Pull request by bill7pearl**
### In this project I have:

-Followed Git & GitHub workflows.
-Configured HTML & CSS Linters, NPM packages, Webhint and Lighthouse.
-Added HTML & CSS files to test the Linters and fix errors.
-Added a README file based on the provided template.
-Added a gitignore file to ignore npm_packages and test.md file.
-Created my first Pull request.

### CODE REVIEW

**Review by codecaiine — CHANGES_REQUESTED** [review]
Hi @bill7pearl , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Great project implementation :heavy_check_mark: 
- Professional and descriptive PR :heavy_check_mark: 
- Good commits history :heavy_check_mark: 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [ ] [OPTIONAL] Please for your next project, please make sure that your branch name is descriptive and has the name of a feature or action e.g. `project_setup` instead of `feature` :+1: 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- NA
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bill7pearl** [comment]
@codecaiine Hello,
I've closed this pull request by mistake and also I've messed it up, can I work with a different Pull request?
also, I'm really having difficulties to configure Linters but I'm working on it.

**Comment by codecaiine** [comment]
Hi @bill7pearl Please don't open a new pull request . You can submit this one for re-review . Always submit the same pull request until it gets approved.  And next time pay attention and do not close/merge the PR until get approved.

**Comment by codecaiine** [comment]
Hi @bill7pearl please check this docs about reverting a PR https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/reverting-a-pull-request

**Review by fobadara — APPROVED** [review]
Hi @bill7pearl, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ Passing linters
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bill7pearl** [comment]
@fobadara Thank you so much,
regarding the branch name, I tried to rename it but it will result the closure of the pull request because I've closed it by mistake in the 1st time, after Googling around it's a GitHub bug apparently.

**Pull request merged**
